databases:
  - name: shopsphere-db
    plan: free
    region: singapore
    postgresMajorVersion: 18

services:
  - type: web
    name: shopsphere
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/products
    autoDeployTrigger: commit
    envVars:
      - key: DB_URL_RAW
        fromDatabase:
          name: shopsphere-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: shopsphere-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: shopsphere-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@shopsphere.local
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: PORT
        value: "10000"
